[build]
  base = "."
  command = "npm run build"
  publish = "dist/ricosabor-tienda/browser"

[build.environment]
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_FETCH_RETRIES = "5"
  NPM_CONFIG_FETCH_RETRY_FACTOR = "2"
  NPM_CONFIG_FETCH_RETRY_MINTIMEOUT = "20000"
  NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT = "120000"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/api-proxy/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
