[build]
  base = "."
  command = "npm run build"
  publish = "dist/ricosabor-tienda/browser"

[functions]
  directory = "netlify/functions"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
